call AssembleChip1613ST.bat
call AssembleMario16.bat
call AssembleMiniMaxiClock.bat
call AssembleMiniMaxiDataScroll.bat
call AssembleShowCompImage.bat
call AssembleShowImage.bat
call AssembleSierpinski.bat